export type ParityStatus = "available" | "partial" | "planned";

export type QtSourceContract = {
  sourcePath: string;
  window: string;
  data: string;
  controls: readonly string[];
  interactions: readonly string[];
};

export type QtUseCase = {
  id: number;
  example: string;
  capability: string;
  status: ParityStatus;
  webSurface: string;
  href: string;
  remaining: string;
  contract: QtSourceContract;
};

/**
 * Source-level inventory of every executable reference example.
 *
 * A use case is "available" only when its dedicated route preserves the Qt
 * example's layout, defaults, sample scale, and user interactions. A grouped
 * demo that merely contains a related capability is never sufficient.
 */
export const QT_USE_CASES: readonly QtUseCase[] = [
  {
    id: 1,
    example: "Basic map with markers",
    capability: "Map setup, markers, base visibility, country boundaries",
    status: "partial",
    webSurface: "Dedicated basic-map example",
    href: "/vector.html?example=01",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/01_basic_map_with_markers.py",
      window: "1024×768; controls above map; center 37,-120 at zoom 6",
      data: "Four named West Coast city points",
      controls: ["Countries off", "Boundary color #334155", "OSM on", "Black background off"],
      interactions: ["Select city", "Toggle packaged countries and lakes", "Change stroke color"],
    },
  },
  {
    id: 2,
    example: "Layer types and styling",
    capability: "Points, icons, circles, lines, polygons, ellipses",
    status: "partial",
    webSurface: "Dedicated layer-types example",
    href: "/vector.html?example=02",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/02_layer_types_and_styling.py",
      window: "1200×800; full map; San Francisco at zoom 10",
      data: "Styled points/icons, 5 km circle, line, triangle, and 3×1.5 km 45° ellipse",
      controls: [],
      interactions: ["Select configured vector features"],
    },
  },
  {
    id: 3,
    example: "Fast points performance",
    capability: "Large canvas point sets and spatial selection",
    status: "partial",
    webSurface: "Dedicated fast-points example",
    href: "/vector.html?example=03",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/03_fast_points_performance.py",
      window: "1200×800; western US at zoom 6",
      data: "10,000 seeded western-US points; red/blue split by latitude",
      controls: [],
      interactions: ["Click selection", "Modifier selection", "Drag-box selection"],
    },
  },
  {
    id: 4,
    example: "WMS and base layers",
    capability: "WMS, XYZ/base source, visibility, opacity",
    status: "partial",
    webSurface: "Dedicated layer-manager example",
    href: "/csv.html?example=04",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/04_wms_and_base_layers.py",
      window: "1200×800; layer controls above map",
      data: "US capital markers plus OSM, AWS terrain, and ahocevar WMS presets",
      controls: ["Generic tile URL presets", "WMS dataset", "Per-layer visibility and opacity"],
      interactions: ["Apply a generic tile source", "Switch the WMS dataset"],
    },
  },
  {
    id: 5,
    example: "Raster overlay",
    capability: "Two georeferenced in-memory images with independent polygon masks",
    status: "partial",
    webSurface: "Dedicated raster-overlay example",
    href: "/raster.html?example=05",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/05_raster_overlay.py",
      window: "1200×800; controls above SF map at zoom 10",
      data: "Two 512×512 heatmaps with 30% horizontal geographic overlap",
      controls: ["Independent six-shape selectors", "Update Mask", "Opacity 0.60 and 0.35"],
      interactions: ["Apply each mask independently", "Adjust each persistent raster layer"],
    },
  },
  {
    id: 6,
    example: "Geo uncertainty ellipses",
    capability: "Fast geographic points with uncertainty geometry",
    status: "partial",
    webSurface: "Dedicated uncertainty example",
    href: "/vector.html?example=06",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/06_geo_uncertainty_ellipses.py",
      window: "1200×800; San Francisco at zoom 11",
      data: "50 seeded fast geographic points with semi-axes and tilt",
      controls: ["Show uncertainty ellipses"],
      interactions: ["Toggle ellipses", "Select fast points"],
    },
  },
  {
    id: 7,
    example: "Feature selection",
    capability: "Click, modifier click, and box selection across layer types",
    status: "partial",
    webSurface: "Dedicated multi-layer selection example",
    href: "/vector.html?example=07",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/07_feature_selection.py",
      window: "1200×800; San Francisco at zoom 10",
      data: "3 vector, 100 fast, and 30 fast-geo points",
      controls: [],
      interactions: ["Plain click replaces", "Ctrl/Cmd click toggles", "Ctrl/Cmd drag selects"],
    },
  },
  {
    id: 8,
    example: "Table integration",
    capability: "Bidirectional map/table selection and deletion",
    status: "partial",
    webSurface: "Dedicated map-table integration example",
    href: "/csv.html?example=08",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/08_table_integration.py",
      window: "1600×900; controls, table, and map in three columns",
      data: "Initial three cities; vector/fast/geo dynamic additions",
      controls: ["Add counts", "Ellipse toggles", "Delete selected"],
      interactions: ["Map↔table selection", "Table context menu", "Delete key"],
    },
  },
  {
    id: 9,
    example: "Selection and recoloring",
    capability: "Recolor selected features across three layer types",
    status: "partial",
    webSurface: "Dedicated recoloring example",
    href: "/vector.html?example=09",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/09_selection_and_recoloring.py",
      window: "1400×900; controls above SF map at zoom 10",
      data: "5 vector points, a selectable gradient track, 100 fast points, and 50 geo points",
      controls: ["Eight QColor recolor buttons"],
      interactions: ["Select across layers", "Recolor only current selection"],
    },
  },
  {
    id: 10,
    example: "Range slider filtering",
    capability: "Numeric and timestamp range filters",
    status: "partial",
    webSurface: "Dedicated range-filter example",
    href: "/filtering.html?example=10",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/10_range_slider_filtering.py",
      window: "1400×900; sliders above 1:2 table/map splitter",
      data: "5,000 seeded points; values 0–100; timestamps across Jan 2024",
      controls: ["Value dual range", "ISO timestamp dual range", "Reset All Filters"],
      interactions: ["Live fast-mask filtering", "Sortable table", "Bidirectional range-capable selection"],
    },
  },
  {
    id: 11,
    example: "Measurement tool",
    capability: "Geodesic segments, total distance, and clear",
    status: "partial",
    webSurface: "Dedicated measurement example",
    href: "/csv.html?example=11",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/11_measurement_tool.py",
      window: "1300×800; map beside typed measurement summary",
      data: "Three blue San Francisco reference landmarks",
      controls: ["Enable/disable measurement", "Clear"],
      interactions: ["Click geodesic path", "List segment and cumulative distances"],
    },
  },
  {
    id: 12,
    example: "Coordinate display",
    capability: "Live latitude/longitude display",
    status: "partial",
    webSurface: "Dedicated coordinate-display example",
    href: "/csv.html?example=12",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/12_coordinate_display.py",
      window: "1200×800; controls above SF map at zoom 10",
      data: "Three city reference points",
      controls: ["Coordinate display enabled"],
      interactions: ["Pointer movement updates formatted coordinate overlay"],
    },
  },
  {
    id: 13,
    example: "Dual table linking",
    capability: "Parent/child multi-table selection",
    status: "partial",
    webSurface: "Dedicated dual-table linking example",
    href: "/linked-tables.html?example=13",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/13_dual_table_linking.py",
      window: "1700×920; map above region/site tabs",
      data: "10 region parents with 10,000 spatial sites each",
      controls: ["Regions tab", "Sites tab"],
      interactions: ["Parent selection fans out", "Child subset clears parent selection"],
    },
  },
  {
    id: 14,
    example: "Delayed render interrupt",
    capability: "Debounced, cancellable expensive raster rendering",
    status: "partial",
    webSurface: "Dedicated delayed-raster example",
    href: "/raster.html?example=14",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/14_delayed_render_interrupt.py",
      window: "1200×860; controls above map",
      data: "Fixed geographic heat field clipped by one exact irregular polygon",
      controls: ["Quality 1–5"],
      interactions: ["250 ms extent debounce", "220 ms render debounce", "Hard interrupt stale work"],
    },
  },
  {
    id: 15,
    example: "Load data and zoom",
    capability: "Fit map to loaded vector and raster data",
    status: "partial",
    webSurface: "Dedicated load-and-zoom example",
    href: "/csv.html?example=15",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/15_load_data_and_zoom.py",
      window: "1200×800; controls above world map",
      data: "Six exact California points and one exact raster footprint",
      controls: ["Load Sample Data", "Zoom to Loaded Data", "Load Raster", "Reset"],
      interactions: ["Fit with padding 48, max zoom 6, duration 250 ms"],
    },
  },
  {
    id: 16,
    example: "Metadata-only table linking",
    capability: "Mapped parents linked to non-spatial child rows",
    status: "partial",
    webSurface: "Dedicated metadata-linking example",
    href: "/linked-tables.html?example=16",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/16_metadata_only_table_linking.py",
      window: "1750×940; map above parent/metadata tabs",
      data: "100,000 FastGeo parents; 3–5 non-spatial rows per parent",
      controls: ["Parents tab", "Metadata tab"],
      interactions: ["Selection links without child map features", "Initial first-five selection"],
    },
  },
  {
    id: 17,
    example: "Map right-click context menu",
    capability: "Coordinate and feature context actions",
    status: "partial",
    webSurface: "Dedicated context-menu example",
    href: "/events.html?example=17",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/17_map_right_click_context_menu.py",
      window: "1100×700; map only; San Francisco at zoom 11",
      data: "Three exact blue starting points",
      controls: [],
      interactions: ["Create point here", "Open point dialog when applicable", "Copy coordinates"],
    },
  },
  {
    id: 18,
    example: "Gradient track speed",
    capability: "Per-segment, per-vertex, and explicit-color gradient lines",
    status: "partial",
    webSurface: "Dedicated gradient-track example",
    href: "/vector.html?example=18",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/18_gradient_track_speed.py",
      window: "1280×820; San Francisco at zoom 13",
      data: "Three exact tracks: segment values, vertex values, and explicit segment colors",
      controls: [],
      interactions: ["Select gradient tracks"],
    },
  },
  {
    id: 19,
    example: "Virtual feature table",
    capability: "Large lazy table and range selection",
    status: "partial",
    webSurface: "Dedicated virtual-table example",
    href: "/csv.html?example=19",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/19_virtual_feature_table.py",
      window: "700×500; standalone table",
      data: "250,000 lazy rows with three exact columns",
      controls: ["Select rows 10–20"],
      interactions: ["Virtual scrolling", "Extended range selection", "Feature-ID selection"],
    },
  },
  {
    id: 20,
    example: "Time histogram slider",
    capability: "Histogram, movable filter window, and global view range",
    status: "partial",
    webSurface: "Dedicated time-histogram example",
    href: "/csv.html?example=20",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/20_time_histogram_slider.py",
      window: "1400×900; table left, map and histogram right",
      data: "6,000 seeded points in four exact time clusters",
      controls: ["Filter window", "Movable fixed window", "Global start/stop", "Reset"],
      interactions: ["Histogram refines with global range", "Map/table filtering remains synchronized"],
    },
  },
  {
    id: 21,
    example: "Movable vector features",
    capability: "Whole-object and vertex geometry movement",
    status: "partial",
    webSurface: "Dedicated movable-vector example",
    href: "/vector.html?example=21",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/21_movable_vector_features.py",
      window: "1100×800; US view at zoom 4",
      data: "Exact movable/fixed points, icons, lines, gradients, polygons, circles, and ellipses",
      controls: [],
      interactions: ["Whole-feature translation", "Existing-vertex movement", "Fixed feature rejection"],
    },
  },
  {
    id: 22,
    example: "Modified map clicks",
    capability: "Modifier and held-key click bindings",
    status: "partial",
    webSurface: "Dedicated modified-click example",
    href: "/events.html?example=22",
    remaining: "Source parity verification in progress.",
    contract: {
      sourcePath: "examples/22_modified_map_clicks.py",
      window: "1000×700; instructions and status above SF map at zoom 11",
      data: "Dynamically created yellow and orange target points",
      controls: ["Clear targets"],
      interactions: ["Click reports coordinate/modifiers/keys", "T click target", "Shift+T browser-safe priority target"],
    },
  },
];
